# Generated by Django 5.2.1 on 2025-11-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=5)),
                ('team', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('room', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rights', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_begins', models.TimeField()),
                ('reservation_ends', models.TimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.space')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.usergroup'),
        ),
    ]
