# Generated by Django 5.2.1 on 2025-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rights', models.CharField(max_length=200)),
            ],
        ),
    ]
