# Generated by Django 5.2.1 on 2025-11-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='person',
            new_name='person_id',
        ),
    ]
