# Generated by Django 5.2.1 on 2025-11-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_begins', models.TimeField()),
                ('reservation_ends', models.TimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.person')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.space')),
            ],
        ),
    ]
