"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url

from pathlib import Path

from dotenv import load_dotenv

# Lataa ympäristömuuttujat .env-tiedostosta
load_dotenv()  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Kehitysvaiheessa .envissä true, tuotannossa false
DEBUG = os.getenv('DEBUG','False')=='True'

# ALLOWED_HOSTS = [
#     host.strip()
#     for host in os.getenv(
#         'ALLOWED_HOSTS',
#         '127.0.0.1 localhost',
#     ).split(',')
# ]

#ALLOWED_HOSTS = tuple(os.getenv('ALLOWED_HOSTS','127.0.0.1 localhost').split())
# TODO: Tarkista Renderin yhteydessä tämä 
ALLOWED_HOSTS = ['tilavaraus.onrender.com','127.0.0.1 localhost']

# ALLOWED_HOSTS = [
#     'tilavaraus.onrender.com',
#     'localhost',
#     '127.0.0.1',
# ]

# Turvallisuusasetukset tuotantoon mennessä

CSRF_TRUSTED_ORIGINS = [
    'https://tilavaraus.onrender.com'
]

# TODO: tarkista ovatko kaikki tarpeellisia
SECURE_SSL_REDIRECT = not DEBUG

SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_SECURE = not DEBUG

SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition
# TODO: tarkista tarvitaanko corsheaders
INSTALLED_APPS = [
    # Djangon sovellukset
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Kolmannen osapuolen sovellukset
    'rest_framework',
    'drf_yasg',
    'whitenoise.runserver_nostatic',
    # TODO: tarkista authtokenin tarpeellisuus ja sijainti
    'rest_framework.authtoken',

    # Paikalliset sovellukset
    'tilavaraus',  
    ]

# Huom! Middelwaressa whitenoisen oltava heti alussa securityn jälkeen
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',?
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES={
#     'default':dj_database_url.config(default=os.getenv('DATABASE_URL')),
# }
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    ),
}

# DATABASES = {
#     'default':dj_database_url.config(default=os.getenv('DATABASE_URL')),
# }
print(os.getenv('DATABASE_URL'))
#print(os.getenv('DB_ENGINE'))

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Helsinki'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
   BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#TODO tarkista mikä on oikea login_redirect_url tässä, reservation alkuperäinen
# Where user is redirected after login/logout and which url to use for login
LOGIN_REDIRECT_URL='/reservations/' 
#LOGIN_REDIRECT_URL='/' 
LOGOUT_REDIRECT_URL='/login/'
LOGIN_URL='/login/'

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],

}

# TODO: katso on ko cors tarpeellinen tässä projekstissa, esim kopioitu
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React frontend (Vite)
#     "http://127.0.0.1:5173",  # Try adding this too
# ]